/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 04 15:57:28 GMT 2023
 */

package org.apache.commons.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;


public class ValidatorEvoTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Validator validator0 = null;
      try {
        validator0 = new Validator((ValidatorResources) null, "fc/OVh3VES.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Resources cannot be null.
         //
         verifyException("org.apache.commons.validator.Validator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Validator validator0 = null;
      try {
        validator0 = new Validator((ValidatorResources) null, (String) null, (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Resources cannot be null.
         //
         verifyException("org.apache.commons.validator.Validator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Validator validator0 = null;
      try {
        validator0 = new Validator((ValidatorResources) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Resources cannot be null.
         //
         verifyException("org.apache.commons.validator.Validator", e);
      }
  }
}
