/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 04 15:55:59 GMT 2023
 */

package org.apache.commons.validator;

import org.junit.Test;


public class ValidatorExceptionEvoTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ValidatorException validatorException0 = new ValidatorException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ValidatorException validatorException0 = new ValidatorException("");
  }
}
